name: serieperfecta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  path_provider: ^2.1.0
  provider: ^6.1.2 

  uuid: ^4.4.0 

  cupertino_icons: ^1.0.6
  hive_flutter: ^1.1.0
  just_audio: ^0.9.36
  vibration: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/bip.mp3
    - assets/sounds/ding.mp3
    - assets/sounds/warning.mp3
